routes/web.php
<?php

/**
 * Public Routes
 *
 */
Route::get('/', 'Auth\LoginController@showLoginForm');
Route::get('/menu', 'HomeController@index')->name('menu');
Route::get('/careers', 'HomeController@careers')->name('careers');
Auth::routes();

/**
 * Routes that require user to be logged in
 * filtered by middleware auth in controller
 */
Route::get('/', 'DashboardController@index');
Route::get('/dashboard', 'DashboardController@index')->name('dashboard');
Route::get('/non-plantilla', 'JobsController@nonPlantilla')->name('jobs.nonplantilla');
Route::get('evaluation/rating', 'EvaluationController@rating')->name('evaluation.rating');
Route::get('jobs/publish', 'JobsController@publish')->name('jobs.publish');
Route::get('evaluation/matrix-qualification', 'EvaluationController@matrixQualification')->name('evaluation.matrix');
Route::get('evaluation/comparative-ranking', 'EvaluationController@comparativeRanking')->name('evaluation.comparative');
Route::get('evaluation/report', 'EvaluationController@evaluationReport')->name('evaluation.report');

Route::post('evaluation/store-matrix-qualification',
    'EvaluationController@storeMatrixQualification')->name('evaluation.storeMatrix');

Route::post('evaluation/store-comparative-ranking',
    'EvaluationController@storeComparativeRanking')->name('evaluation.storeComparative');

Route::resources([
    'applicant' => 'ApplicantController',
    'config' => 'ConfigController',
    'evaluation' => 'EvaluationController',
    'jobs' => 'JobsController',
    'recommendation' => 'RecommendationController',
    'appointment' => 'AppointmentController',
    'joboffer' => 'JobOfferController',
    'assumption' => 'AssumptionController',
    'attestation' => 'AttestationController',
    'report' => 'ReportController',
]);

resources/views/layouts/_dashboard.blade.php
<body>
   <div class="be-wrapper be-fixed-sidebar">
        @include('layouts._top-bar')
        @include('layouts._left-sidebar')
        @include('layouts._main-content')
        @include('layouts._right-sidebar')
   </div>
   <script src="{{ URL::asset('beagle-assets/lib/jquery/jquery.min.js') }}" type="text/javascript"></script>
   <script src="{{ URL::asset('beagle-assets/lib/perfect-scrollbar/js/perfect-scrollbar.jquery.min.js') }}" type="text/javascript"></script>
   <script src="{{ URL::asset('beagle-assets/lib/bootstrap/dist/js/bootstrap.bundle.min.js') }}" type="text/javascript"></script>
   <script src="{{ URL::asset('beagle-assets/js/app.js') }}" type="text/javascript"></script>
   @yield('scripts')
</body>

resources/views/layouts/_flash-message.blade.php
@if ($message = Session::get('success'))
<div class="row">
    <div class="col-12">
        <div role="alert" class="alert alert-contrast alert-success alert-dismissible">
            <div class="icon"><span class="mdi mdi-check"></span></div>
            <div class="message">
                <button type="button" data-dismiss="alert" aria-label="Close" class="close">
                    <span aria-hidden="true" class="mdi mdi-close"></span>
                </button>
                <strong>Good!</strong> {{ $message }}
            </div>
        </div>
    </div>
</div>
@endif


@if ($message = Session::get('error'))
<div class="row">
    <div class="col-12">
        <div role="alert" class="alert alert-contrast alert-danger alert-dismissible">
            <div class="icon"><span class="mdi mdi-close-circle-o"></span></div>
            <div class="message">
                <button type="button" data-dismiss="alert" aria-label="Close" class="close">
                    <span aria-hidden="true" class="mdi mdi-close"></span>
                </button>
                <strong>Danger!</strong> {{ $message }}
            </div>
        </div>
    </div>
</div>
@endif


@if ($message = Session::get('warning'))
<div class="row">
    <div class="col-12">
        <div role="alert" class="alert alert-contrast alert-warning alert-dismissible">
            <div class="icon"><span class="mdi mdi-alert-triangle"></span></div>
            <div class="message">
                <button type="button" data-dismiss="alert" aria-label="Close" class="close">
                    <span aria-hidden="true" class="mdi mdi-close"></span>
                </button>
                <strong>Warning!</strong> {{ $message }}
            </div>
        </div>
    </div>
</div>
@endif


@if ($message = Session::get('info'))
<div class="row">
    <div class="col-12">
        <div role="alert" class="alert alert-contrast alert-primary alert-dismissible">
            <div class="icon"><span class="mdi mdi-info-outline"></span></div>
            <div class="message">
                <button type="button" data-dismiss="alert" aria-label="Close" class="close">
                    <span aria-hidden="true" class="mdi mdi-close"></span>
                </button>
                <strong>Info!</strong> {{ $message }}
            </div>
        </div>
    </div>
</div>
@endif

@if ($errors->any())
    <div class="row">
        <div class="col-12">
            @foreach ($errors->all() as $error)
                <div role="alert" class="alert alert-contrast alert-danger alert-dismissible">
                    <div class="icon"><span class="mdi mdi-close-circle-o"></span></div>
                    <div class="message">
                        <button type="button" data-dismiss="alert" aria-label="Close" class="close">
                            <span aria-hidden="true" class="mdi mdi-close"></span>
                        </button>
                        <strong>Danger!</strong> {{ $error }}
                    </div>
                </div>
            @endforeach
        </div>
    </div>
@endif

resources/views/layouts/_left-sidebar.blade.php
<!-- Left Sidebar -->
<div class="be-left-sidebar">
  <div class="left-sidebar-wrapper">
    <a href="#" class="left-sidebar-toggle">Dashboard</a>
    <div class="left-sidebar-spacer">
      <div class="left-sidebar-scroll">
        <div class="left-sidebar-content">
          <ul class="sidebar-elements">
            <li class="divider">Menu</li>
            <li class="active">
              <a href="{{ route('dashboard') }}"><i class="icon mdi mdi-home"> </i><span>Dashboard</span></a>
            </li>
            <li class="parent">
              <a href="#"><i class="icon mdi mdi-stackoverflow"> </i><span>Vacant Positions</span></a>
              <ul class="sub-menu">
                <li><a href="{{ route('jobs.index') }}">Plantilla</a></li>
                <li><a href="{{ route('jobs.nonplantilla') }}">Non-Plantilla</a></li>
              </ul>
            </li>

            <li class="parent">
              <a href="#"><i class="icon mdi mdi-face"> </i><span>Applicants</span></a>
              <ul class="sub-menu">
                <li><a href="{{ route('applicant.index') }}">List applicants</a></li>
              </ul>
            </li>

            <li class="parent">
              <a href="#"><i class="icon mdi mdi-star-circle"> </i><span>Evaluation</span></a>
              <ul class="sub-menu">
                <li><a href="{{ route('evaluation.matrix') }}">Matrix of Qualification</a></li>
                <li><a href="{{ route('evaluation.index') }}">Evaluation</a></li>
                <li><a href="{{ route('evaluation.comparative') }}">Comparative Ranking Summary</a></li>
              </ul>
            </li>

            <li><a href="{{ route('recommendation.index') }}"><i class="icon mdi mdi-assignment-account"> </i>
                <span>Recommendation</span></a></li>

            <li><a href="{{ route('appointment.index') }}"><i class="icon mdi mdi-calendar"> </i>
                <span>Appointment</span></a></li>

            <li class="parent">
              <a href="#"><i class="icon mdi mdi-badge-check"> </i><span>Job Offer</span></a>
              <ul class="sub-menu">
                <li><a href="{{ route('joboffer.index') }}">Plantilla</a></li>
                <li><a href="{{ route('joboffer.index', ['status'=>'non-plantilla']) }}">Non-Plantilla</a></li>
              </ul>
            </li>

            <li><a href="{{ route('assumption.index') }}"><i class="icon mdi mdi-star-circle"> </i>
                <span>Assumption to Duty</span></a></li>

            <li><a href="{{ route('attestation.index') }}"><i class="icon mdi mdi-assignment"> </i>
                <span>Transmittal for Attestation</span></a></li>

            <li><a href="{{ route('report.index') }}"><i class="icon mdi mdi-assignment-o"> </i>
                <span>Reports</span></a></li>
            @if(Auth::id() == config('params._SUPER_ADMIN_ID_'))
              <li class="parent">
                <a href="#"><i class="icon mdi mdi-settings"> </i><span>Configurations</span></a>
                <ul class="sub-menu">
                  <li><a href="{{ route('config.index') }}">List configurations</a></li>
                </ul>
              </li>
              <li class="divider">Features</li>
              <li class="parent">
                <a href="#"><i class="icon mdi mdi-inbox"> </i><span>Public Pages</span></a>
                <ul class="sub-menu">
                  <li><a href="{{ route('menu') }}">Menu</a></li>
                  <li><a href="{{ route('careers') }}">Careers</a></li>
                </ul>
              </li>
            @endif
          </ul>
        </div>
      </div>
    </div>

    <div class="progress-widget">
      <div class="progress-data"><span class="progress-value">70%</span><span class="name">Current Project</span>
      </div>
      <div class="progress">
        <div style="width: 60%;" class="progress-bar progress-bar-primary"></div>
      </div>
    </div>
  </div>
</div>
<!-- /. Left Sidebar -->

resources/views/layouts/_main-content.blade.php
<div class="be-content">
    <div class="main-content container-fluid">
        @include('layouts._flash-message')
        @yield('content')
    </div>
</div>

resources/views/layouts/_print-body.blade.php
<body style="background-color: white !important;">
   <div class="be-wrapper be-nosidebar-left">
        @include('layouts._main-content')
   </div>
   <script src="{{ URL::asset('beagle-assets/lib/jquery/jquery.min.js') }}" type="text/javascript"></script>
   <script src="{{ URL::asset('beagle-assets/lib/perfect-scrollbar/js/perfect-scrollbar.jquery.min.js') }}" type="text/javascript"></script>
   <script src="{{ URL::asset('beagle-assets/lib/bootstrap/dist/js/bootstrap.bundle.min.js') }}" type="text/javascript"></script>
   <script src="{{ URL::asset('beagle-assets/js/app.js') }}" type="text/javascript"></script>
   @yield('scripts')
</body>

resources/views/layouts/_splash.blade.php
<body class="be-splash-screen">
@yield('content')
<script src="{{ URL::asset('beagle-assets/lib/jquery/jquery.min.js') }}" type="text/javascript"></script>
<script src="{{ URL::asset('beagle-assets/lib/perfect-scrollbar/js/perfect-scrollbar.jquery.min.js') }}"
        type="text/javascript"></script>
<script src="{{ URL::asset('beagle-assets/lib/bootstrap/dist/js/bootstrap.bundle.min.js') }}"
        type="text/javascript"></script>
<script src="{{ URL::asset('beagle-assets/js/app.js') }}" type="text/javascript"></script>
@yield('scripts')
<footer>
    <div class="container-fluid">
        <div class="row">
            <div class="col bg-primary text-center text-light h-25">
                <h4>Powered By: e2e Solutions Management Phils. Inc. &copy;</h4></div>
        </div>
    </div>
</footer>
</body>

resources/views/layouts/_top-bar.blade.php
<nav class="navbar navbar-expand fixed-top be-top-header">
    <div class="container-fluid">
        <div class="be-navbar-header"><a href="{{ route('dashboard') }}" class="navbar-brand"></a></div>
        <div class="be-right-navbar">
            <ul class="nav navbar-nav float-right be-user-nav">
                <li class="nav-item dropdown">
                    <a href="#" data-toggle="dropdown" role="button" aria-expanded="false" class="nav-link dropdown-toggle"><img src="{{ URL::asset('beagle-assets/img/avatar.png') }}" alt="Avatar"><span class="user-name">Túpac Amaru</span></a>
                    <div role="menu" class="dropdown-menu">
                        <div class="user-info">
                            <div class="user-name">{{ Auth::user()->name }}</div>
                            <div class="user-position online">Available</div>
                        </div>
                        <a href="pages-profile.html" class="dropdown-item"><span class="icon mdi mdi-face"></span> Account</a>
                        <a href="#" class="dropdown-item"><span class="icon mdi mdi-settings"></span> Settings</a>
                        <a href="{{ route('logout') }}"  class="dropdown-item" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                        <span class="icon mdi mdi-power"></span> Logout
                        </a>
                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                            {{ csrf_field() }}
                        </form>
                    </div>
                </li>
            </ul>
            <div class="page-title"><span>{{ $title }}</span></div>
            <ul class="nav navbar-nav float-right be-icons-nav">
                <li class="nav-item dropdown"><a href="#" role="button" aria-expanded="false" class="nav-link be-toggle-right-sidebar"><span class="icon mdi mdi-settings"></span></a></li>
                <li class="nav-item dropdown">
                    <a href="#" data-toggle="dropdown" role="button" aria-expanded="false" class="nav-link dropdown-toggle"><span class="icon mdi mdi-notifications"></span><span class="indicator"></span></a>
                    <ul class="dropdown-menu be-notifications">
                        <li>
                            <div class="title">Notifications<span class="badge badge-pill">3</span></div>
                            <div class="list">
                                <div class="be-scroller">
                                    <div class="content">
                                        <ul>
                                            <li class="notification notification-unread">
                                                <a href="#">
                                                    <div class="image"><img src="{{ URL::asset('beagle-assets/img/avatar2.png') }}" alt="Avatar"></div>
                                                    <div class="notification-info">
                                                        <div class="text"><span class="user-name">Jessica Caruso</span> accepted your invitation to join the team.</div>
                                                        <span class="date">2 min ago</span>
                                                    </div>
                                                </a>
                                            </li>
                                            <li class="notification">
                                                <a href="#">
                                                    <div class="image"><img src="{{ URL::asset('beagle-assets/img/avatar3.png') }}" alt="Avatar"></div>
                                                    <div class="notification-info">
                                                        <div class="text"><span class="user-name">Joel King</span> is now following you</div>
                                                        <span class="date">2 days ago</span>
                                                    </div>
                                                </a>
                                            </li>
                                            <li class="notification">
                                                <a href="#">
                                                    <div class="image"><img src="{{ URL::asset('beagle-assets/img/avatar4.png') }}" alt="Avatar"></div>
                                                    <div class="notification-info">
                                                        <div class="text"><span class="user-name">John Doe</span> is watching your main repository</div>
                                                        <span class="date">2 days ago</span>
                                                    </div>
                                                </a>
                                            </li>
                                            <li class="notification">
                                                <a href="#">
                                                    <div class="image"><img src="{{ URL::asset('beagle-assets/img/avatar5.png') }}" alt="Avatar"></div>
                                                    <div class="notification-info">
                                                        <span class="text"><span class="user-name">Emily Carter</span> is now following you</span><span class="date">5 days ago</span>
                                                    </div>
                                                </a>
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                            <div class="footer"> <a href="#">View all notifications</a></div>
                        </li>
                    </ul>
                </li>
                <li class="nav-item dropdown">
                    <a href="#" data-toggle="dropdown" role="button" aria-expanded="false" class="nav-link dropdown-toggle"><span class="icon mdi mdi-apps"></span></a>
                    <ul class="dropdown-menu be-connections">
                        <li>
                            <div class="list">
                                <div class="content">
                                    <div class="row">
                                        <div class="col"><a href="#" class="connection-item"><img src="{{ URL::asset('beagle-assets/img/github.png') }}" alt="Github"><span>GitHub</span></a></div>
                                        <div class="col"><a href="#" class="connection-item"><img src="{{ URL::asset('beagle-assets/img/bitbucket.png') }}" alt="Bitbucket"><span>Bitbucket</span></a></div>
                                        <div class="col"><a href="#" class="connection-item"><img src="{{ URL::asset('beagle-assets/img/slack.png') }}" alt="Slack"><span>Slack</span></a></div>
                                    </div>
                                    <div class="row">
                                        <div class="col"><a href="#" class="connection-item"><img src="{{ URL::asset('beagle-assets/img/dribbble.png') }}" alt="Dribbble"><span>Dribbble</span></a></div>
                                        <div class="col"><a href="#" class="connection-item"><img src="{{ URL::asset('beagle-assets/img/mail_chimp.png') }}" alt="Mail Chimp"><span>Mail Chimp</span></a></div>
                                        <div class="col"><a href="#" class="connection-item"><img src="{{ URL::asset('beagle-assets/img/dropbox.png') }}" alt="Dropbox"><span>Dropbox</span></a></div>
                                    </div>
                                </div>
                            </div>
                            <div class="footer"> <a href="#">More</a></div>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="description" content="">
        <meta name="author" content="">
        <link rel="shortcut icon" href="{{ URL::asset('beagle-assets/img/logo-fav.png') }}">
            <!-- CSRF Token -->
        <meta name="csrf-token" content="{{ csrf_token() }}">

        <title>{{ config('app.name', 'E2E RMS') }}</title>
        <link rel="stylesheet" type="text/css" href="{{ URL::asset('beagle-assets/lib/perfect-scrollbar/css/perfect-scrollbar.min.css') }}"/>
        <link rel="stylesheet" type="text/css" href="{{ URL::asset('beagle-assets/lib/material-design-icons/css/material-design-iconic-font.min.css') }}"/><!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
        @yield('css')
        <link rel="stylesheet" href="{{ URL::asset('beagle-assets/css/app.css') }}" type="text/css"/>
    </head>
    @if(Auth::check())
        @include('layouts._dashboard')
    @else
        @include('layouts._splash')
    @endif
</html>

resources/views/layouts/print.blade.php
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="description" content="">
        <meta name="author" content="">
        <link rel="shortcut icon" href="{{ URL::asset('beagle-assets/img/logo-fav.png') }}">
            <!-- CSRF Token -->
        <meta name="csrf-token" content="{{ csrf_token() }}">

        <title>{{ config('app.name', 'E2E RMS') }}</title>
        <link rel="stylesheet" type="text/css" href="{{ URL::asset('beagle-assets/lib/perfect-scrollbar/css/perfect-scrollbar.min.css') }}"/>
        <link rel="stylesheet" type="text/css" href="{{ URL::asset('beagle-assets/lib/material-design-icons/css/material-design-iconic-font.min.css') }}"/><!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
        @yield('css')
        <link rel="stylesheet" href="{{ URL::asset('beagle-assets/css/app.css') }}" type="text/css"/>
    </head>
    @include('layouts._print-body')
</html>